services:
  type:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    command: mypy /app/src/clockodo_mcp /app/tests

  lint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    command: >
      pylint /app/src/clockodo_mcp /app/tests

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    env_file: .env.example
    command: >
      pytest --cov-report=term-missing
      --cov-report=xml:/tmp/.coverage.xml
      --cov-config=/app/setup.cfg
      --cov=clockodo_mcp
      --junitxml=/tmp/.junit.xml /app/tests

  style-check:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    command: black --check /app/src/clockodo_mcp /app/tests

  jupyter:
    image: quay.io/jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: sh -c "pip install python-dotenv && start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
